### PR TITLE
espanso now has case propagation

### PR DESCRIPTION
**Pull request by femtocept**
espanso added an option for entries in 0.5.1 where you can capitalize the first or all letters of a trigger and have the replacement correspond.

i added it to every entry. it seems appropriate for a misspelling package for whole words.

I don't know why it says my commits have line deletions, if you look at the diffs you can see I have only either added the line "    case_propagation: true" to all entries or changed the version number to 1.0.2.

Thank you for your wonderful package, I hope this is a welcome addition.

Bryan Mosher

### CODE REVIEW

**Comment by timorunge** [comment]
Thank you @femtocept! 

I've adopted the auto code which is automatically generating the files (take a look at 94c1d333280b2a4acfab54552e8581c3827868d9) and published a new version.

**Comment by femtocept** [comment]
Oh cool, I was wondering what the Go was for. I just used a vim macro to insert the line throughout 😆 . Your way sounds better. I did something similar using google sheets to concatenate the yaml text.

Thank you for the update! I'm a teacher during this viral crisis and Google Classroom leaves a lot to be desired. The en_US package helps me maintain consistency for my new American students from abroad who don't know there are alternate spellings of words. You're helping them too.

**Comment by femtocept** [comment]
I could leave an issue on the espanso hub asking Frederico to update your packages if you'd like.

**Comment by timorunge** [comment]
> You're helping them too.

Actually I think it's @federico-terzi who's helping with espanso. This module is just a small part of a great piece of software. :)

> I could leave an issue on the espanso hub asking Frederico to update your packages if you'd like.

Actually the package is already updated. At least if you're installing it directly via `espanso package install`. But what's actually missing is an update functionality for hub.espanso.org which still lists an old version and also some functionality to update all packages from espanso hub. 

I will create some follow up for this in the next days.

**Comment by federico-terzi** [comment]
Hey guys,
Thank you for your contributions! I'm glad to see we are building a small community :)
I'll make sure to update the version on the hub in the next few days.

Thanks for your help :)

**Comment by timorunge** [comment]
@federico-terzi: Some thoughts on the hub generally speaking. We can also take this offline or to an issue in your repository.

Since you're validating the packages manually in the first place and adding them to the hub there is a missing process for "updates" of the packages. Actually I like that not everyone can add a new package to the hub and that it needs some kind of "review" from your side. That's a great thing. 

This is not happening for updates. So whenever someone is pushing a new version for the packages `espanso package install` is downloading the latest version / the version which is defined `package_version`. I think this should only happening from "trusted sources". And / or after a review from your side.
This would also prevent to have a gap between the homepage which is listing one version and the actual package manager which is downloading another one.

Another side note: some `espanso package update` functionality would be great. :)

**Comment by federico-terzi** [comment]
Hey @timorunge,
> This is not happening for updates. So whenever someone is pushing a new version for the packages espanso package install is downloading the latest version / the version which is defined package_version. I think this should only happening from "trusted sources". And / or after a review from your side.
This would also prevent to have a gap between the homepage which is listing one version and the actual package manager which is downloading another one.

Thank you for pointing this out. I thought about this exact issue about a month ago, realizing that this could become a security problem in the long run. For this reason, since espanso 0.5.4 packages have now an additional layer of security. Check out the [release](https://github.com/federico-terzi/espanso/releases/tag/v0.5.4).

The idea is basically that most packages are now copied over [espanso hub core](https://github.com/federico-terzi/espanso-hub-core) and are downloaded from there.

In fact, the only packages that are not on the core are your packages! For a couple of reasons:
* Being quite big they could make the repo too large (in the current implementation, when downloading a package espanso downloads the whole repository).
* I trust you :)

That said, the whole package system in espanso is still **very** rough. Once this gets some more traction, we could think about creating a service like Pypi.

Let me know what you think :)

**Comment by federico-terzi** [comment]
> Another side note: some espanso package update functionality would be great. :)

This would be indeed a great idea, I'll open an issue :)

**Comment by timorunge** [comment]
Hey @federico-terzi,

> Thank you for pointing this out. I thought about this exact issue about a month ago, realizing that this could become a security problem in the long run. For this reason, since espanso 0.5.4 packages have now an additional layer of security. Check out the [release](https://github.com/federico-terzi/espanso/releases/tag/v0.5.4).

Ha, to be honest I'm not reading the release notes. I should have done it. I just realised the same after doing the change in this repository over here.

Actually I like the change. On the other side it will make the maintenance of packages difficult for:
- You. Since you have to maintain all packages at the same time
- Others. Since they have to do PRs to the repo that you need to verify once again.

I think a good - and more or less working - approach is how the maintainer from the Dracula theme is handling this (https://github.com/dracula). Having one repository which is holding the themes for different applications itself (https://github.com/dracula) as submodules while every theme for every application is still a single git repository where you can - if required - assign the ownership. 

In this particular case you can also stay with the current implementation of

```rust
let zip_url = repo_url.to_owned() + "/archive/master.zip";
```

but also have a separation and download just the package which was asked by the user. 

> In fact, the only packages that are not on the core are your packages! For a couple of reasons:

Ha, I don't wanna be an exception! ;)

> * Being quite big they could make the repo too large (in the current implementation, when downloading a package espanso downloads the whole repository).

The actual size of this repository is just about 2.5M. Gzip compressed it's only 212K (257K downloaded from GitHub). Since you're already using `zip` as a compression method during the download why are you not considering to move to `.tar.gz`? 

The difference here is quite significant: `72K` for zip and `50K` for `tar.gz` while using using  https://github.com/federico-terzi/espanso-hub-core/archive/master.zip vs. https://github.com/federico-terzi/espanso-hub-core/archive/master.tar.gz. 

I have no experience with Rust but if I'll find some time I'll try to dig in a little bit. :)
> * I trust you :)

Thanks. But you should only trust yourself. And not even that! ;)
> Let me know what you think :)

Here you are! Feel free to contact me on the known ways if you wanna discuss things further and if you need a second opinion on some things. :)

**Comment by federico-terzi** [comment]
> Actually I like the change. On the other side it will make the maintenance of packages difficult for:
> 
> * You. Since you have to maintain all packages at the same time
> * Others. Since they have to do PRs to the repo that you need to verify once again.
> 
> I think a good - and more or less working - approach is how the maintainer from the Dracula theme is handling this (https://github.com/dracula). Having one repository which is holding the themes for different applications itself (https://github.com/dracula) as submodules while every theme for every application is still a single git repository where you can - if required - assign the ownership.

Thank you so much for suggesting this Timo, this is a wonderful solution. Shame on me I didn't think about git submodules! Also the fact that each submodule is tied to a particular commit is perfect for this use case. 
At this point, my only concern is whether a user could rewrite the repo history so that the commit check becomes ineffective (that of would be a problem security-wise).

> In this particular case you can also stay with the current implementation of
> 
> ```rust
> let zip_url = repo_url.to_owned() + "/archive/master.zip";
> ```
> 
> but also have a separation and download just the package which was asked by the user.

I totally agree, that would make the process much more efficient when installing a single package.

> Ha, I don't wanna be an exception! ;)

Sorry about that :)

> The actual size of this repository is just about 2.5M. Gzip compressed it's only 212K (257K downloaded from GitHub). Since you're already using `zip` as a compression method during the download why are you not considering to move to `.tar.gz`?
> 
> The difference here is quite significant: `72K` for zip and `50K` for `tar.gz` while using using https://github.com/federico-terzi/espanso-hub-core/archive/master.zip vs. https://github.com/federico-terzi/espanso-hub-core/archive/master.tar.gz.
> 

This is another great suggestion! I didn't know GitHub offered tar.gz archives as well. I'll open an issue for that :)

**Comment by timorunge** [comment]
Since we're moving the conversation over to the espanso repos I'm closing this issue right now. 

Thank you @femtocept for the PR.
Thank you @federico-terzi for the heads up.

**Pull request closed without merging**
